# This is an example travis-ci config. It contains more than you need.
# See the readme for how to enable travis-ci builds.

sudo: false
language: ruby
rvm:
  - 2.5
  - 2.6

branches:
  only:
    - master
    - develop

before_install: gem install bundler

script:
  - bundle exec rspec

# This adds an additional 'build' that is just the rubocop run
matrix:
  include:
    - rvm: ruby-head
      script: bin/rubocop
