version: '3'

services:

  dev:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems

  mongo_dev:
    image: mongo
    volumes:
      - data_db:/data/db

  mongo_test:
    image: mongo


volumes:
  gem_cache:
  data_db:
