version: '3'

services:

  dev:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    environment:
      DB_CONNECTION_STRING: "mysql2://ht_repository:ht_repository@mariadb/ht_repository"

  mongo_dev:
    image: mongo
    volumes:
      - data_db:/data/db

  mongo_test:
    image: mongo

  mariadb:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

volumes:
  gem_cache:
  data_db:
