version: '3'

services:

  dev:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems

  mongo_dev:
    image: mongo
    volumes:
      - data_db:/data/db
    command: --replSet rs0 --bind_ip localhost,mongo_dev

  mongo_test:
    image: mongo
    command: --replSet rs0 --bind_ip localhost,mongo_test

volumes:
  gem_cache:
  data_db:
