version: '3'

services:

  dev:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    environment:
      MYSQL_CONNECTION_STRING: "mysql2://ht_repository:ht_repository@mariadb/ht_repository"

  mongo_dev:
    image: mongo
    volumes:
      - data_db:/data/db
    command: --replSet rs0 --bind_ip localhost,mongo_dev
    volumes:
      - ./bin:/tmp/bin

  mongo_test:
    image: mongo
    command: --replSet rs0 --bind_ip localhost,mongo_test
    volumes:
      - ./bin:/tmp/bin

  mariadb:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"

volumes:
  gem_cache:
  data_db:
