version: '3'

services:

  dev:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems

  mongo:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - data_db:/data/db

volumes:
  gem_cache:
  data_db:
