---

x-condition-healthy: &healthy
  condition: service_healthy

x-healthcheck-defaults: &healthcheck-defaults
  interval: 5s
  timeout: 10s
  start_period: 10s
  retries: 5

x-holdings-container: &holdings-container-defaults
  build:
    context: .
    target: dev
  volumes:
    - .:/usr/src/app
    - gem_cache:/gems
  command: bundle exec rspec
  environment: &holdings-default-environment
    MARIADB_HOLDINGS_RW_HOST: mariadb
    MARIADB_HOLDINGS_RW_USERNAME: root
    MARIADB_HOLDINGS_RW_PASSWORD: holdings
    MARIADB_HOLDINGS_RW_DATABASE: holdings_dev
    MARIADB_HATHIFILES_RW_HOST: mariadb
    MARIADB_HATHIFILES_RW_USERNAME: root
    MARIADB_HATHIFILES_RW_PASSWORD: holdings
    MARIADB_HATHIFILES_RW_DATABASE: holdings_dev
    PUSHGATEWAY: http://pushgateway:9091
    DATABASE_ENV: development
  depends_on:
    mariadb: *healthy
    redis: *healthy

services:

  test:
    <<: *holdings-container-defaults
    command: bundle exec rspec
    environment: 
      <<: *holdings-default-environment
      DATABASE_ENV: test
      MARIADB_HATHIFILES_RW_DATABASE: holdings_test
      MARIADB_HOLDINGS_RW_DATABASE: holdings_test
    depends_on: 
      mariadb: *healthy
      redis: *healthy

  dev:
    <<: *holdings-container-defaults
    command: sleep infinity

  phctl: 
    <<: *holdings-container-defaults
    entrypoint: bundle exec ruby bin/phctl.rb

  processor:
    <<: *holdings-container-defaults
    restart: always
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
      - ./example/datasets:/tmp/datasets
    command: bundle exec sidekiq -c 1 -r ./lib/sidekiq_jobs.rb

  mariadb:
    image: mariadb:10.5
    environment:
      MARIADB_ROOT_PASSWORD: holdings
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "healthcheck.sh", "--su-mysql", "--connect", "--innodb_initialized" ]

  pushgateway:
    image: prom/pushgateway
    command:
      - --web.enable-admin-api
    ports:
      - 9091:9091
    healthcheck:
      <<: *healthcheck-defaults
      test: [ "CMD", "wget", "--quiet", "--tries=1", "-O", "/dev/null", "pushgateway:9091/-/healthy" ]

  sidekiq_web:
    <<: *holdings-container-defaults
    restart: always
    command: bundle exec puma bin/sidekiq_web.ru
    depends_on:
      redis: *healthy
    ports:
      - 9292:9292
    environment:
      REDIS_URL: redis://redis/

  redis:
    image: redis
    restart: always
    healthcheck:
      <<: *healthcheck-defaults
      test: ["CMD", "redis-cli","ping"]

volumes:
  gem_cache:
  data_db:
