version: '3'

services:

  dev:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    environment:
      MYSQL_CONNECTION_STRING: "mysql2://ht_repository:ht_repository@mariadb/ht_repository"
      PUSHGATEWAY: http://pushgateway:9091

  mongo_dev:
    image: mongo:5.0.9
    volumes:
      - data_db:/data/db
    command: --replSet rs0 --bind_ip localhost,mongo_dev
    volumes:
      - ./bin:/tmp/bin

  mongo_test:
    image: mongo:5.0.9
    command: --replSet rs0 --bind_ip localhost,mongo_test
    volumes:
      - ./bin:/tmp/bin

  mariadb:
    image: mariadb
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

  pushgateway:
    image: prom/pushgateway
    ports:
      - "9091:9091"

  sidekiq_web:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    command: bundle exec puma bin/sidekiq_web.ru
    depends_on:
      - redis
    ports:
      - 9292:9292
    environment:
      REDIS_URL: redis://redis/

  redis:
    image: redis
    restart: always

volumes:
  gem_cache:
  data_db:
