version: '3'

services:

  test:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    environment:
      MYSQL_CONNECTION_STRING: "mysql2://ht_repository:ht_repository@mariadb/ht_repository"
      PUSHGATEWAY: http://pushgateway:9091
      MONGOID_ENV: test
    profiles:
      - test
    depends_on:
      - redis
      - mongo_test
      - mariadb
      - pushgateway

  phctl:
    build: .
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    environment:
      MYSQL_CONNECTION_STRING: "mysql2://ht_repository:ht_repository@mariadb/ht_repository"
      PUSHGATEWAY: http://pushgateway:9091
      MONGOID_ENV: development
    entrypoint: bundle exec ruby bin/phctl.rb
    profiles:
      - phctl
    depends_on:
      - redis
      - mongo_dev
      - mariadb
      - processor

  processor:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
      - ./example/datasets:/tmp/datasets
    command: bundle exec sidekiq -c 1 -r ./lib/sidekiq_jobs.rb
    environment:
      MYSQL_CONNECTION_STRING: "mysql2://ht_repository:ht_repository@mariadb/ht_repository"
      PUSHGATEWAY: http://pushgateway:9091
      MONGOID_ENV: development
    depends_on:
      - redis
      - mongo_dev
      - mariadb
      - pushgateway

  mongo_dev:
    image: mongo:6.0.2
    command: --replSet rs0 --bind_ip localhost,mongo_dev
    volumes:
      - data_db:/data/db
      - ./bin:/tmp/bin

  mongo_test:
    image: mongo:6.0.2
    command: --replSet rs0 --bind_ip localhost,mongo_test
    volumes:
      - ./bin:/tmp/bin
    profiles:
      - test

  mariadb:
    image: mariadb
    environment:
      MARIADB_ROOT_PASSWORD: mariadbroot
    healthcheck:
      test: ["CMD", "mariadb-admin", "status", "-uroot", "-pmariadbroot"]
      interval: 5s
      timeout: 10s
      start_period: 30s
      retries: 5
    volumes:
      - ./sql:/docker-entrypoint-initdb.d/

  pushgateway:
    image: prom/pushgateway
    command:
      - --web.enable-admin-api
    ports:
      - 9091:9091
    healthcheck:
      test: ["CMD", "wget", "-q", "http://localhost:9091", "-O","/dev/null"]
      interval: 5s
      timeout: 10s
      start_period: 30s
      retries: 5

  redis:
    image: redis
    restart: always

  sidekiq_web:
    build: .
    restart: always
    volumes:
      - .:/usr/src/app
      - gem_cache:/gems
    command: bundle exec puma bin/sidekiq_web.ru
    depends_on:
      redis:
        condition: service_healthy
    ports:
      - 9292:9292
    environment:
      REDIS_URL: redis://redis/

volumes:
  gem_cache:
  data_db:
