production:
  clients:
    default:
      database: "<%= Settings.mongodb.database %>"
      hosts:
        - "<%= Settings.mongodb.host %>"
      options:
        user: "<%= Settings.mongodb.username %>"
        password: "<%= Settings.mongodb.password %>"
        auth_source: "<%= Settings.mongodb.auth_source %>"
  options:
    raise_not_found_error: false

development:
  clients:
    default:
      database: development
      hosts:
        - mongo_dev:27017
  options:
    raise_not_found_error: false

test:
  clients:
    default:
      database: test
      hosts:
        - mongo_test:27017
  options:
    raise_not_found_error: false
    #    log_level: :debug
