hathifile_path: <%= ENV["HATHIFILE_PATH"] %>
concordance_path: <%= ENV["CONCORDANCE_PATH"] %>
large_cluster_ocns: /usr/src/app/config/large_cluster_ocns.txt
database:
  url: <%= ENV["MYSQL_CONNECTION_STRING"] %>
mongodb:
  host: <%= ENV["MONGODB_HOST"] %>
  password: <%= ENV["MONGODB_PASSWORD"] %>
target_cost: <%= ENV["TARGET_COST"] %>
etas_overlap_reports_path: <%= ENV["ETAS_OVERLAP_REPORTS_PATH"] %>
etas_overlap_reports_remote_path: <%= ENV["ETAS_OVERLAP_REPORTS_REMOTE_PATH"] %>
etas_overlap_batch_size: <%= ENV["ETAS_OVERLAP_BATCH_SIZE"] %>
loading_flag_path: <%= ENV["LOADING_FLAG_PATH"] %>
cost_report_freq_path: <%= ENV["COST_REPORT_FREQ_PATH"] %>
deprecation_report_path: <%= ENV["DEPRECATION_REPORT_PATH"] %>
pushgateway: <%= ENV["PUSHGATEWAY"] %>
rclone_config_path: <%= ENV["RCLONE_CONFIG_PATH"] %>
