concordance_path: <%= ENV["CONCORDANCE_PATH"] %>
cost_report_freq_path: <%= ENV["COST_REPORT_FREQ_PATH"] %>
cost_report_path: <%= ENV["COST_REPORT_PATH"] %>
deprecation_report_path: <%= ENV["DEPRECATION_REPORT_PATH"] %>
estimates_path: <%= ENV["ESTIMATES_PATH"] %>
etas_overlap_batch_size: <%= ENV["ETAS_OVERLAP_BATCH_SIZE"] %>
etas_overlap_reports_path: <%= ENV["ETAS_OVERLAP_REPORTS_PATH"] %>
etas_overlap_reports_remote_path: <%= ENV["ETAS_OVERLAP_REPORTS_REMOTE_PATH"] %>
hathifile_path: <%= ENV["HATHIFILE_PATH"] %>
loading_flag_path: <%= ENV["LOADING_FLAG_PATH"] %>
local_report_path: <%= ENV["LOCAL_REPORT_PATH"] %>
pushgateway: <%= ENV["PUSHGATEWAY"] %>
rclone_config_path: <%= ENV["RCLONE_CONFIG_PATH"] %>
replace_commitment_report_path: <%= ENV["REPLACE_COMMITMENT_REPORT_PATH"] %>
shared_print_report_path: <%= ENV["SHARED_PRINT_REPORT_PATH"] %>
shared_print_update_report_path: <%= ENV["SHARED_PRINT_UPDATE_REPORT_PATH"] %>
target_cost: <%= ENV["TARGET_COST"] %>
