serials_file: <%= ENV["SERIALS_FILE"] %>
hathifile_path: <%= ENV["HATHIFILE_PATH"] %>
holdings_path: <%= ENV["HOLDINGS_PATH"] %>
concordance_path: <%= ENV["CONCORDANCE_PATH"] %>
large_cluster_ocns: /usr/src/app/config/large_cluster_ocns.txt
database:
  url: <%= ENV["MYSQL_CONNECTION_STRING"] %>
mongodb:
  host: <%= ENV["MONGODB_HOST"] %>
  password: <%= ENV["MONGODB_PASSWORD"] %>
target_cost: <%= ENV["TARGET_COST"] %>
etas_overlap_reports_path: <%= ENV["ETAS_OVERLAP_REPORTS_PATH"] %>
loading_flag_path: <%= ENV["LOADING_FLAG_PATH"] %>

