concordance_path: /tmp/concordance
hathifile_path: /tmp/hathifiles
large_cluster_ocns: /tmp/large_cluster_ocns.txt
loading_flag_path: /tmp/loading_flag
slack_endpoint: http://slack.test/endpoint
cost_report_freq_path: /tmp/cost_report_freq
deprecation_report_path: /tmp/deprecation_report
shared_print_update_report_path: /tmp/shared_print_update_report
etas_overlap_batch_size: 50
