concordance_path: <%= ENV["TEST_TMP"] %>/concordance
cost_report_freq_path: <%= ENV["TEST_TMP"] %>/cost_report_freq
cost_report_path: <%= ENV["TEST_TMP"] %>/cost_reports
deprecation_report_path: <%= ENV["TEST_TMP"] %>/deprecation_report
estimates_path: <%= ENV["TEST_TMP"] %>/estimates
etas_overlap_batch_size: 50
etas_overlap_reports_path: <%= ENV["TEST_TMP"] %>/etas_overlap_reports
etas_overlap_reports_remote_path: <%= ENV["TEST_TMP"] %>/etas_overlap_report_remote
hathifile_path: <%= ENV["TEST_TMP"] %>/hathifiles
loading_flag_path: <%= ENV["TEST_TMP"] %>/loading_flag
local_member_data: <%= ENV["TEST_TMP"] %>/local_member_data
local_report_path: <%= ENV["TEST_TMP"] %>/local_reports
oclc_collection_id_map_path: spec/fixtures/oclc_collection_id_map.tsv
oclc_registration_report_path: <%= ENV["TEST_TMP"] %>
rclone_config_path: <%= ENV["TEST_TMP"] %>/rclone.conf
remote_member_data: <%= ENV["TEST_TMP"] %>/remote_member_data
replace_commitment_report_path: <%= ENV["TEST_TMP"] %>/replace_commitment_report
scrub_base_path: <%= ENV["TEST_TMP"] %>/scrub_data
scrub_chunk_count: 4
scrub_chunk_work_dir: <%= ENV["TEST_TMP"] %>
scrub_line_count_diff_max: 0.05
shared_print_report_path: <%= ENV["TEST_TMP"] %>/shared_print_reports
shared_print_update_report_path: <%= ENV["TEST_TMP"] %>/shared_print_update_report
sp_newly_ingested_report_path: <%= ENV["TEST_TMP"] %>/sp_newly_ingested_report
slack_endpoint: http://slack.test/endpoint
target_cost: 9999

