serials_file: /tmp/serials_file
concordance_path: /tmp/concordance
hathifile_path: /tmp/hathifiles
holdings_path: /tmp/holdings_data
large_cluster_ocns: /tmp/large_cluster_ocns.txt
loading_flag_path: /tmp/loading_flag
slack_endpoint: http://slack.test/endpoint
