concordance_path: /tmp/concordance
hathifile_path: /tmp/hathifiles
large_cluster_ocns: /tmp/large_cluster_ocns.txt
loading_flag_path: /tmp/loading_flag
slack_endpoint: http://slack.test/endpoint
cost_report_freq_path: /tmp/cost_report_freq
deprecation_report_path: /tmp/deprecation_report
replace_commitment_report_path: /tmp/replace_commitment_report
shared_print_update_report_path: /tmp/shared_print_update_report
etas_overlap_batch_size: 50
rclone_config_path: /tmp/rclone.conf
oclc_collection_id_map_path: spec/fixtures/oclc_collection_id_map.tsv
oclc_registration_report_path: /tmp

