USE `ht_repository`;

INSERT INTO `ht_institutions` VALUES
('allegheny',NULL,'Allegheny College','allegheny.edu',1,NULL,'allegheny',NULL,NULL,1,'https://idp.allegheny.edu/openathens','AVL',0.67,'us'),
('amherst',NULL,'Amherst College','amherst.edu',1,NULL,'amherst',NULL,NULL,1,'https://shibidp.amherst.edu/idp/shibboleth','AMH',0.67,'us'),
('anu',NULL,'Australian National University','anu.edu.au',0,NULL,'anu',NULL,NULL,1,'https://idp2.anu.edu.au/idp/shibboleth','ANV',1.00,'au'),
('archive',NULL,'Internet Archive','archive.org',1,NULL,'archive',NULL,NULL,2,NULL,NULL,1.00,'us'),
('arizona',NULL,'University of Arizona','arizona.edu',1,NULL,'arizona',NULL,NULL,1,'urn:mace:incommon:arizona.edu','AZU',1.00,'us'),
('asu',NULL,'Arizona State University','asu.edu',1,NULL,'asu',NULL,NULL,1,'urn:mace:incommon:asu.edu','AZS',1.00,'us'),
('aub',NULL,'American University of Beirut','aub.edu.lb',0,NULL,'aub',NULL,NULL,1,'https://idp.aub.edu.lb/idp/shibboleth','LEAUB',0.67,'lb'),
('auburn',NULL,'Auburn University','auburn.edu',1,NULL,'auburn',NULL,NULL,1,'https://webauth.auburn.edu/idp/shibboleth','AAA',1.00,'us'),
('auckland',NULL,'University of Auckland','auckland.ac.nz',0,NULL,'auckland',NULL,NULL,1,'http://iam.auckland.ac.nz/idp','UV0',1.00,'nz'),
('augusta',NULL,'Augusta University','augusta.edu',1,NULL,'usg','University System of Georgia',NULL,1,'https://shfed.augusta.edu/idp/shibboleth','GSL',3.00,'us'),
('baylor',NULL,'Baylor University','baylor.edu',1,NULL,'baylor',NULL,NULL,1,'https://shibboleth-2.baylor.edu/idp/shibboleth','IYU',1.00,'us'),
('bc',NULL,'Boston College','bc.edu',1,NULL,'bc',NULL,NULL,1,'https://login.bc.edu/idp/shibboleth','BXM',1.00,'us'),
('bentley-umich',NULL,'Bentley Historical Library, University of Michigan','bentley.umich.edu',1,NULL,'bentley-umich',NULL,NULL,2,NULL,NULL,1.00,'us'),
('berkeley',NULL,'University of California, Berkeley','berkeley.edu',1,NULL,'universityofcalifornia',NULL,NULL,1,'urn:mace:incommon:berkeley.edu','CUY',1.33,'us'),
('brandeis',NULL,'Brandeis University','brandeis.edu',1,NULL,'brandeis',NULL,NULL,1,'https://shibboleth.brandeis.edu/idp/shibboleth','MBB',0.67,'us'),
('brocku',NULL,'Brock University','brocku.ca',0,NULL,'brocku',NULL,NULL,1,'http://adfs.brocku.ca/adfs/services/trust','BRX',0.67,'ca'),
('brooklynmuseum',NULL,'Brooklyn Museum','brooklynmuseum.org',1,NULL,'brooklynmuseum',NULL,NULL,2,NULL,NULL,1.00,'us'),
('brown',NULL,'Brown University','brown.edu',1,NULL,'brown',NULL,NULL,1,'https://sso.brown.edu/idp/shibboleth','RBN',1.00,'us'),
('brynmawr',NULL,'Bryn Mawr College','brynmawr.edu',1,NULL,'brynmawr',NULL,NULL,1,'https://idp.brynmawr.edu/idp/shibboleth','BMC',0.67,'us'),
('bu',NULL,'Boston University','bu.edu',1,NULL,'bu',NULL,NULL,1,'https://shib.bu.edu/idp/shibboleth','BOS',1.00,'us'),
('bucknell',NULL,'Bucknell University','bucknell.edu',1,NULL,'bucknell',NULL,NULL,1,'https://shib.bucknell.edu/idp/shibboleth','PBU',0.67,'us'),
('buffalo',NULL,'University At Buffalo, The State University of New York','buffalo.edu',1,NULL,'buffalo',NULL,NULL,1,'urn:mace:incommon:buffalo.edu','BUF',1.00,'us'),
('byu',NULL,'Brigham Young University','byu.edu',1,NULL,'byu',NULL,NULL,1,'https://shib.byu.edu/idp/shibboleth','UBY',1.00,'us'),
('carleton',NULL,'Carleton College','carleton.edu',1,NULL,'carleton',NULL,NULL,1,'urn:mace:incommon:carleton.edu','MNN',0.67,'us'),
('carletonu',NULL,'Carleton University','carleton.ca',0,NULL,'carletonu',NULL,NULL,1,'http://cufed.carleton.ca/adfs/services/trust','CEF',1.00,'ca'),
('case',NULL,'Case Western Reserve University','case.edu',1,NULL,'case',NULL,NULL,1,'urn:mace:incommon:case.edu','CWR',1.00,'us'),
('cgu',NULL,'Claremont Graduate University','cgu.edu',1,NULL,'claremont','The Claremont Colleges',NULL,1,'https://webauth.cgu.edu/idp/shibboleth','HDC',1.00,'us'),
('uchicago','CHI','University of Chicago','uchicago.edu',1,NULL,'uchicago',NULL,NULL,1,'urn:mace:incommon:uchicago.edu','CGU',1.33,'us'),
('claremont',NULL,'The Claremont Colleges Services','claremont.edu',1,NULL,'claremont','The Claremont Colleges',NULL,1,'https://webauth.cuc.claremont.edu/idp/shibboleth','HDC',1.00,'us'),
('clarkart',NULL,'Sterling and Francine Clark Art Institute','clarkart.edu',1,NULL,'clarkart',NULL,NULL,2,NULL,NULL,1.00,'us'),
('clements-umich',NULL,'William L. Clements Library, University of Michigan','clements.umich.edu',1,NULL,'clements-umich',NULL,NULL,2,NULL,NULL,1.00,'us'),
('clemson',NULL,'Clemson University','clemson.edu',1,NULL,'clemson',NULL,NULL,1,'urn:mace:incommon:clemson.edu','SEA',1.00,'us'),
('cmc',NULL,'Claremont McKenna College','cmc.edu',1,NULL,'claremont','The Claremont Colleges',NULL,1,'https://webauth.cmc.edu/idp/shibboleth','HDC',1.00,'us'),
('cmich',NULL,'Central Michigan University','cmich.edu',1,NULL,'cmich',NULL,NULL,1,'https://shibboleth.cmich.edu/idp/shibboleth','EZC',0.67,'us'),
('cmu',NULL,'Carnegie Mellon University','cmu.edu',1,NULL,'cmu',NULL,NULL,1,'https://login.cmu.edu/idp/shibboleth','PMC',1.00,'us'),
('colby',NULL,'Colby College','colby.edu',1,NULL,'colby',NULL,NULL,1,'http://www.okta.com/exk1o1pee7gFPgAUf357','CBY',0.67,'us'),
('colorado',NULL,'University of Colorado Boulder','colorado.edu',1,NULL,'colorado',NULL,NULL,1,'https://fedauth.colorado.edu/idp/shibboleth','COD',1.00,'us'),
('columbia','Columbia','Columbia University','columbia.edu',1,NULL,'columbia',NULL,NULL,1,'urn:mace:incommon:columbia.edu','ZCU',1.33,'us'),
('cornell','Cornell','Cornell University','cornell.edu',1,NULL,'cornell',NULL,NULL,1,'https://shibidp.cit.cornell.edu/idp/shibboleth','COO',1.33,'us'),
('cwu',NULL,'Central Washington University','cwu.edu',1,NULL,'cwu',NULL,NULL,1,'https://idp.cwu.edu/idp/shibboleth','CWU',0.67,'us'),
('dartmouth',NULL,'Dartmouth College','dartmouth.edu',1,NULL,'dartmouth',NULL,NULL,1,'urn:mace:incommon:dartmouth.edu','DRB',1.00,'us'),
('depaul',NULL,'DePaul University','depaul.edu',1,NULL,'depaul',NULL,NULL,1,'https://shib.is.depaul.edu/idp/shibboleth','IAC',0.67,'us'),
('depauw',NULL,'Depauw University','depauw.edu',1,NULL,'depauw',NULL,NULL,0,'https://idp.depauw.edu/openathens','IDU',0.67,'us'),
('dickinson',NULL,'Dickinson College','dickinson.edu',1,NULL,'dickinson',NULL,NULL,1,'https://auth.dickinson.edu/idp/shibboleth','DKC',0.67,'us'),
('duke',NULL,'Duke University','duke.edu',1,NULL,'duke',NULL,NULL,1,'urn:mace:incommon:duke.edu','NDD',1.33,'us'),
('elon',NULL,'Elon University','elon.edu',1,NULL,'elon',NULL,NULL,1,'https://idp.elon.edu/idp/shibboleth','NEO',0.67,'us'),
('emory',NULL,'Emory University','emory.edu',1,NULL,'emory',NULL,NULL,1,'https://login.emory.edu/idp/shibboleth','EMU',1.33,'us'),
('fau',NULL,'Florida Atlantic University','fau.edu',1,NULL,'flbog','Florida State University System',NULL,1,'https://sso.fau.edu/idp/shibboleth','',5.00,'us'),
('fgcu',NULL,'Florida Gulf Coast University','fgcu.edu',1,NULL,'fgcu',NULL,NULL,0,'https://sso.fgcu.edu/idp/shibboleth',NULL,1.00,'us'),
('fiu',NULL,'Florida International University','fiu.edu',1,NULL,'flbog','Florida State University System',NULL,1,'https://fiuidp.fiu.edu/idp/shibboleth','',5.00,'us'),
('frick',NULL,'The Frick Collection','frick.org',1,NULL,'frick',NULL,NULL,2,NULL,NULL,1.00,'us'),
('fsu',NULL,'Florida State University','fsu.edu',1,NULL,'flbog','Florida State University System',NULL,1,'https://idp.fsu.edu','',5.00,'us'),
('fsu-dev',NULL,'Florida State University CAS IdP','fsu.edu',1,NULL,'flbog','Florida State University System',NULL,0,'https://idp.fsu.edu','',5.00,'us'),
('flbog',NULL,'State University System of Florida','flbog.edu',1,NULL,'flbog',NULL,NULL,2,NULL,'',5.00,'us'),
('gatech',NULL,'Georgia Institute of Technology','gatech.edu',1,NULL,'usg',NULL,NULL,1,'https://idp.gatech.edu/idp/shibboleth','GSL',3.00,'us'),
('gc-cuny',NULL,'CUNY Graduate School and University Center','gc.cuny.edu',1,NULL,'gc-cuny',NULL,NULL,1,'https://sso.gc.cuny.edu/idp/shibboleth','ZGM',0.67,'us'),
('georgetown',NULL,'Georgetown University','georgetown.edu',1,NULL,'georgetown',NULL,NULL,1,'https://shibb-idp.georgetown.edu/idp/shibboleth','DGU',1.00,'us'),
('getty',NULL,'Getty Research Institute','getty.edu',1,NULL,'getty',NULL,NULL,1,'https://idp.getty.edu/idp','JPG',1.00,'us'),
('gmu',NULL,'George Mason University','gmu.edu',1,NULL,'gmu',NULL,NULL,1,'https://shibboleth.gmu.edu/idp/shibboleth','VGM',1.00,'us'),
('google',NULL,'Google','google.com',0,NULL,'google',NULL,NULL,3,'https://google.cirrusidentity.com/gateway',NULL,1.00,'us'),
('grinnell',NULL,'Grinnell College','grinnell.edu',1,NULL,'grinnell',NULL,NULL,1,'https://idp.grinnell.edu/idp/shibboleth','IOG',0.67,'us'),
('gsu',NULL,'Georgia State University','gsu.edu',1,NULL,'usg','University System of Georgia',NULL,1,'https://idp.gsu.edu/idp/shibboleth','GSL',3.00,'us'),
('harvard','Harvard','Harvard University','harvard.edu',1,NULL,'harvard',NULL,NULL,1,'https://fed.huit.harvard.edu/idp/shibboleth','HUL',1.33,'us'),
('hathitrust',NULL,'HathiTrust','hathitrust.org',1,NULL,'hathitrust',NULL,NULL,2,NULL,'',0.00,'us'),
('haverford',NULL,'Haverford College','haverford.edu',1,NULL,'haverford',NULL,NULL,1,'https://idp.haverford.edu/idp/shibboleth','HVC',0.67,'us'),
('hawaii',NULL,'University of Hawaii','hawaii.edu',1,NULL,'hawaii',NULL,NULL,1,'https://idp.hawaii.edu/idp/shibboleth','HUH',1.00,'us'),
('hmc',NULL,'Harvey Mudd College','hmc.edu',1,NULL,'claremont','The Claremont Colleges',NULL,1,'https://identity.hmc.edu/idp','HDC',1.00,'us'),
('ht_private',NULL,'Private Donor','',0,NULL,'ht_private',NULL,NULL,2,NULL,NULL,1.00,'us'),
('ht_support-microsoft',NULL,'Digitization Support from Microsoft','',0,NULL,'ht_support-microsoft',NULL,NULL,2,NULL,NULL,1.00,'us'),
('ias',NULL,'IAS, via Princeton University','ias.edu',1,'princeton.edu','princeton','Princeton University','https://idp.princeton.edu/idp/shibboleth',1,'https://idp.ias.edu/idp/shibboleth','PUL',1.33,'us'),
('iastate',NULL,'Iowa State University','iastate.edu',1,NULL,'iastate',NULL,NULL,1,'https://idp.iastate.edu/shibboleth','IWA',1.00,'us'),
('iu','IND','Indiana University','iu.edu',1,NULL,'iu',NULL,NULL,1,'urn:mace:incommon:iu.edu','IUL',1.33,'us'),
('uiowa','IOWA','University of Iowa','uiowa.edu',1,NULL,'uiowa',NULL,NULL,1,'urn:mace:incommon:uiowa.edu','NUI',1.33,'us'),
('jhu',NULL,'Johns Hopkins University','jhu.edu',1,NULL,'jhu',NULL,NULL,1,'urn:mace:incommon:johnshopkins.edu','JHE',1.33,'us'),
('keio','Keio','Keio University','keio.ac.jp',0,NULL,'keio',NULL,NULL,2,NULL,NULL,1.00,'us'),
('kennesaw',NULL,'Kennesaw State University','kennesaw.edu',1,'usg','usg','University System of Georgia',NULL,1,'https://idp-samlprod3.kennesaw.edu','GSL',3.00,'us'),
('kenyon',NULL,'Kenyon College','kenyon.edu',1,NULL,'kenyon',NULL,NULL,1,'https://sso.kenyon.edu/idp/shibboleth',NULL,1.00,'us'),
('kgi',NULL,'Keck Graduate Institute of Applied Life Sciences','kgi.edu',1,NULL,'claremont','The Claremont Colleges',NULL,1,'https://webauth.kgi.edu/idp/shibboleth','HDC',1.00,'us'),
('knowledgeunlatched',NULL,'Knowledge Unlatched','knowledgeunlatched.org',0,NULL,'knowledgeunlatched',NULL,NULL,2,NULL,NULL,1.00,'us'),
('ksu',NULL,'Kansas State University','ksu.edu',1,NULL,'ksu',NULL,NULL,1,'https://signin.k-state.edu/idp/shibboleth','KKS',1.00,'us'),
('ku',NULL,'University of Kansas','ku.edu',1,NULL,'ku',NULL,NULL,1,'https://shibidp.ku.edu/idp/shibboleth','KKU',1.00,'us'),
('lafayette',NULL,'Lafayette College','lafayette.edu',1,NULL,'lafayette',NULL,NULL,1,'urn:mace:incommon:lafayette.edu','LAF',0.67,'us'),
('laurentian',NULL,'Laurentian University','laurentian.ca',0,NULL,'laurentian',NULL,NULL,1,'https://connect.laurentian.ca/idp',NULL,1.00,'us'),
('lehigh',NULL,'Lehigh University','lehigh.edu',1,NULL,'lehigh',NULL,NULL,1,'https://sso.cc.lehigh.edu/sso/saml2/idp/metadata.php','LYU',0.67,'us'),
('loc',NULL,'Library of Congress','loc.gov',1,NULL,'loc',NULL,NULL,1,'https://idpvlp01.loc.gov/idp/shibboleth','DLC',1.33,'us'),
('loc-dev',NULL,'Library of Congress Staging IdP','loc.gov',1,NULL,'loc-dev',NULL,NULL,0,'https://c1vlsidp01.loc.gov/idp/shibboleth',NULL,1.00,'us'),
('luc',NULL,'Loyola University of Chicago','luc.edu',1,NULL,'luc',NULL,NULL,0,'https://shibidp.luc.edu/idp/shibboleth',NULL,1.00,'us'),
('macalester',NULL,'Macalester College','macalester.edu',1,NULL,'macalester',NULL,NULL,1,'https://idp.macalester.edu/openathens','MAC',0.67,'us'),
('mcgill',NULL,'McGill University','mcgill.ca',0,NULL,'mcgill',NULL,NULL,1,'https://shibboleth.mcgill.ca/idp/shibboleth','LGG',1.00,'ca'),
('mcmaster',NULL,'McMaster University','mcmaster.ca',0,NULL,'mcmaster',NULL,NULL,1,'https://sso.mcmaster.ca/idp/shibboleth','MUH',1.00,'ca'),
('mdanderson',NULL,'University of Texas M.D. Anderson Cancer Center','mdanderson.org',1,NULL,'utexas','The University of Texas',NULL,1,'https://shib.mdanderson.org/idp/shibboleth','IXA',3.00,'us'),
('miami',NULL,'University of Miami','miami.edu',1,NULL,'miami',NULL,NULL,1,'https://caneid.miami.edu/idp/shibboleth','FQG',1.00,'us'),
('milproj-dc-umich',NULL,'Millennium Project','milproj.dc.umich.edu',1,NULL,'milproj-dc-umich',NULL,NULL,2,NULL,NULL,1.00,'us'),
('umn','MINN','University of Minnesota','umn.edu',1,NULL,'umn',NULL,NULL,1,'urn:mace:incommon:umn.edu','MNU',1.33,'us'),
('missouri',NULL,'University of Missouri - Columbia','missouri.edu',1,NULL,'missouri',NULL,NULL,1,'https://shib-idp.umsystem.edu/idp/shibboleth','MUU',1.00,'us'),
('mit',NULL,'Massachusetts Institute of Technology','mit.edu',1,NULL,'mit',NULL,NULL,1,'urn:mace:incommon:mit.edu','MYG',1.00,'us'),
('mndigital',NULL,'Minnesota Digital Library','mndigital.org',1,NULL,'mndigital',NULL,NULL,2,NULL,NULL,1.00,'us'),
('mnhs',NULL,'Minnesota Historical Society','mnhs.org',1,NULL,'mnhs',NULL,NULL,2,NULL,NULL,1.00,'us'),
('monash',NULL,'Monash University','monash.edu',0,NULL,'monash',NULL,NULL,1,'http://www.okta.com/exk375o7dgmAtaMBE2p7','LM1',1.00,'au'),
('montana',NULL,'Montana State University','montana.edu',1,NULL,'montana',NULL,NULL,1,'https://login.montana.edu/idp/shibboleth','MZF',0.67,'us'),
('msstate',NULL,'Mississippi State University','msstate.edu',1,NULL,'msstate',NULL,NULL,1,'https://shibboleth.its.msstate.edu/idp/shibboleth','MFM',1.00,'us'),
('msu','MSU','Michigan State University','msu.edu',1,NULL,'msu',NULL,NULL,1,'urn:mace:incommon:msu.edu','EEM',1.00,'us'),
('mtholyoke',NULL,'Mount Holyoke College','mtholyoke.edu',1,NULL,'mtholyoke',NULL,NULL,1,'https://idp.mtholyoke.edu/idp/shibboleth','MTH',0.67,'us'),
('nccu',NULL,'North Carolina Central University','nccu.edu',1,NULL,'nccu',NULL,NULL,0,'https://idp.nccu.edu/idp/shibboleth',NULL,1.00,'us'),
('ncl',NULL,'National Central Library','ncl.edu.tw',0,NULL,'ncl',NULL,NULL,2,NULL,NULL,1.00,'us'),
('ncsu',NULL,'North Carolina State University','ncsu.edu',1,NULL,'ncsu',NULL,NULL,1,'urn:mace:incommon:ncsu.edu','NRC',1.00,'us'),
('nd',NULL,'University of Notre Dame','nd.edu',1,NULL,'nd',NULL,NULL,1,'https://login.nd.edu/idp/shibboleth','IND',1.00,'us'),
('neu',NULL,'Northeastern University','neu.edu',1,NULL,'neu',NULL,NULL,1,'https://neuidmsso.neu.edu/idp/shibboleth','ILU',1.00,'us'),
('nfb',NULL,'National Federation of the Blind','nfb.org',1,NULL,'nfb',NULL,NULL,1,'pumex-idp',NULL,1.00,'us'),
('nmsu',NULL,'New Mexico State University - Las Cruces Campus','nmsu.edu',1,NULL,'nmsu',NULL,NULL,1,'https://myidp.nmsu.edu','IRU',0.67,'us'),
('northwestern','NWU','Northwestern University','northwestern.edu',1,NULL,'northwestern',NULL,NULL,1,'urn:mace:incommon:northwestern.edu','INU',1.33,'us'),
('nypl','NYPL','New York Public Library','nypl.org',1,NULL,'nypl',NULL,NULL,2,NULL,'NYP',1.33,'us'),
('nyu',NULL,'New York University','nyu.edu',1,NULL,'nyu',NULL,NULL,1,'urn:mace:incommon:nyu.edu','ZYU',1.33,'us'),
('okstate',NULL,'Oklahoma State University','okstate.edu',1,NULL,'okstate',NULL,NULL,1,'https://idp.okstate.edu/idp/shibboleth','oks',1.00,'us'),
('olemiss',NULL,'University of Mississippi','olemiss.edu',1,NULL,'olemiss',NULL,NULL,1,'https://umshibp.olemiss.edu/idp/shibboleth','MUM',1.00,'us'),
('osu','OSU','The Ohio State University','osu.edu',1,NULL,'osu',NULL,NULL,1,'urn:mace:incommon:osu.edu','OSU',1.00,'us'),
('ou',NULL,'University of Oklahoma','ou.edu',1,NULL,'ou',NULL,NULL,1,'https://shib.ou.edu/idp/shibboleth','OKU',1.00,'us'),
('ox',NULL,'University of Oxford','ox.ac.uk',0,NULL,'ox',NULL,NULL,1,'https://registry.shibboleth.ox.ac.uk/idp','EQO',1.33,'uk'),
('pfw',NULL,'Purdue University Fort Wayne','pfw.edu',1,NULL,'purdue','Purdue University',NULL,1,'https://shibadprod.pfw.edu/idp/shibboleth','IPL',1.00,'us'),
('pitt',NULL,'University of Pittsburgh','pitt.edu',1,NULL,'pitt',NULL,NULL,1,'https://passport.pitt.edu/idp/shibboleth','PIT',1.33,'us'),
('pitzer',NULL,'Pitzer College','pitzer.edu',1,NULL,'claremont','The Claremont Colleges',NULL,1,'https://webauth.pitzer.edu/idp/shibboleth','HDC',1.00,'us'),
('pomona',NULL,'Pomona College','pomona.edu',1,NULL,'claremont','The Claremont Colleges',NULL,1,'https://websso.pomona.edu/','HDC',1.00,'us'),
('press-umich',NULL,'University of Michigan Press','press.umich.edu',1,NULL,'press-umich',NULL,NULL,2,NULL,NULL,1.00,'us'),
('princeton','PRNC','Princeton University','princeton.edu',1,NULL,'princeton',NULL,NULL,1,'https://idp.princeton.edu/idp/shibboleth','PUL',1.33,'us'),
('psu','PSU','Pennsylvania State University','psu.edu',1,NULL,'psu',NULL,NULL,1,'urn:mace:incommon:psu.edu','UPM',1.33,'us'),
('purdue','PURD','Purdue University','purdue.edu',1,NULL,'purdue',NULL,NULL,1,'https://idp.purdue.edu/idp/shibboleth','IPL',1.00,'us'),
('queensu',NULL,'Queen\'s University','queensu.ca',0,NULL,'queensu',NULL,NULL,1,'https://login.queensu.ca/idp/shibboleth','CNEDL',1.00,'ca'),
('reed',NULL,'Reed College','reed.edu',1,NULL,'reed',NULL,NULL,1,'https://idp.reed.edu/idp/shibboleth','ORC',0.67,'us'),
('richmond',NULL,'University of Richmond','richmond.edu',1,NULL,'richmond',NULL,NULL,1,'urn:mace:incommon:richmond.edu','VRU',0.67,'us'),
('rochester',NULL,'University of Rochester','rochester.edu',1,NULL,'rochester',NULL,NULL,1,'https://shib2.its.rochester.edu/idp/shibboleth','RRR',1.00,'us'),
('rutgers',NULL,'Rutgers University','rutgers.edu',1,NULL,'rutgers',NULL,NULL,1,'urn:mace:incommon:rutgers.edu','NJR',1.00,'us'),
('ryerson',NULL,'Ryerson University','ryerson.ca',0,NULL,'ryerson',NULL,NULL,1,'https://idp.ccs.ryerson.ca/idp/shibboleth','RRP',0.67,'ca'),
('sc',NULL,'University of South Carolina','sc.edu',1,NULL,'sc',NULL,NULL,1,'urn:mace:incommon:sc.edu','SUC',1.00,'us'),
('scrippscollege',NULL,'Scripps College','scrippscollege.edu',1,NULL,'claremont','The Claremont Colleges',NULL,1,'https://webauth.scrippscollege.edu/idp/shibboleth','HDC',1.00,'us'),
('sjsu',NULL,'San Jose State University','sjsu.edu',1,NULL,'sjsu',NULL,NULL,1,'https://idp01.sjsu.edu/idp/shibboleth','CSJ',0.67,'us'),
('smith',NULL,'Smith College','smith.edu',1,NULL,'smith',NULL,NULL,1,'https://login.smith.edu/idp/shibboleth','snn',0.67,'us'),
('smu',NULL,'Southern Methodist University','smu.edu',1,NULL,'smu',NULL,NULL,1,'https://idp.smu.edu/idp/shibboleth','ISM',1.00,'us'),
('stanford',NULL,'Stanford University','stanford.edu',1,NULL,'stanford',NULL,NULL,1,'urn:mace:incommon:stanford.edu','STF',1.33,'us'),
('swarthmore',NULL,'Swarthmore College','swarthmore.edu',1,NULL,'swarthmore',NULL,NULL,1,'https://sid.swarthmore.edu/idp/shibboleth','PSC',0.67,'us'),
('swmed',NULL,'University of Texas Southwestern Medical Center','swmed.edu',1,NULL,'utexas','The University of Texas',NULL,1,'https://shib2.swmed.edu/idp/shibboleth','IXA',3.00,'us'),
('sydney',NULL,'University of Sydney','sydney.edu.au',0,NULL,'sydney',NULL,NULL,1,'https://federation.sydney.edu.au/idp/shibboleth','LS1',1.00,'au'),
('syr',NULL,'Syracuse University','syr.edu',1,NULL,'syr',NULL,NULL,1,'https://shibidp.syr.edu/idp/shibboleth','SYB',1.00,'us'),
('tamu',NULL,'Texas A&amp;M University','tamu.edu',1,NULL,'tamu',NULL,NULL,1,'urn:mace:incommon:tamu.edu','TXA',1.33,'us'),
('tcu',NULL,'Texas Christian University','tcu.edu',1,NULL,'tcu',NULL,NULL,1,'https://idp.tcu.edu/idp','ICU',0.67,'us'),
('technicalreports',NULL,'Technical Report Archive &amp; Image Library','technicalreports.org',1,NULL,'technicalreports',NULL,NULL,2,NULL,NULL,1.00,'us'),
('temple',NULL,'Temple University','temple.edu',1,NULL,'temple',NULL,NULL,1,'https://fim.temple.edu/idp/shibboleth','TEU',1.00,'us'),
('trincoll',NULL,'Trinity College','trincoll.edu',1,NULL,'trincoll',NULL,NULL,1,'https://shibboleth.trincoll.edu/idp/shibboleth','TYC',0.67,'us'),
('ttu',NULL,'Texas Tech University','ttu.edu',1,NULL,'ttu',NULL,NULL,1,'https://idp.shibboleth.ttu.edu/idp/shibboleth','NED',1.00,'us'),
('tufts',NULL,'Tufts University','tufts.edu',1,NULL,'tufts',NULL,NULL,1,'https://shib-idp.tufts.edu/idp/shibboleth','TFW',1.00,'us'),
('tulane',NULL,'Tulane University','tulane.edu',1,NULL,'tulane',NULL,NULL,1,'https://idp.tulane.edu/idp/shibboleth','LRU',1.00,'us'),
('txstate',NULL,'Texas State University - San Marcos','txstate.edu',1,NULL,'txstate',NULL,NULL,1,'https://authentic.txstate.edu/idp/shibboleth','TXI',1.00,'us'),
('ua',NULL,'University of Alabama','ua.edu',1,NULL,'ua',NULL,NULL,1,'https://idp.ua.edu/idp/shibboleth','ALM',1.00,'us'),
('ualberta',NULL,'University of Alberta','ualberta.ca',0,NULL,'ualberta',NULL,NULL,1,'https://login.ualberta.ca/saml2/idp/metadata.php','UAB',1.33,'ca'),
('ualberta-test',NULL,'University of Alberta (Testing)','ualberta.ca',0,NULL,'ualberta-test',NULL,NULL,0,'https://login.ualberta.ca/saml2/idp/metadata.php',NULL,1.00,'us'),
('ubc',NULL,'University of British Columbia','ubc.ca',0,NULL,'ubc',NULL,NULL,1,'https://authentication.ubc.ca','UBC',1.00,'ca'),
('uc',NULL,'University of Cincinnati','uc.edu',1,NULL,'uc',NULL,NULL,1,'https://login.uc.edu/idp/shibboleth','CIN',1.00,'us'),
('ucalgary',NULL,'University of Calgary','ucalgary.ca',0,NULL,'ucalgary',NULL,NULL,1,'https://shibboleth.ucalgary.ca/idp/shibboleth','UAU',1.00,'ca'),
('ucdavis',NULL,'University of California, Davis','ucdavis.edu',1,NULL,'universityofcalifornia',NULL,NULL,1,'urn:mace:incommon:ucdavis.edu','CUV',1.00,'us'),
('ucf',NULL,'University of Central Florida','ucf.edu',1,NULL,'flbog','Florida State University System',NULL,1,'https://idp-prod.cc.ucf.edu/idp/shibboleth','',5.00,'us'),
('uci',NULL,'University of California, Irvine','uci.edu',1,NULL,'universityofcalifornia',NULL,NULL,1,'urn:mace:incommon:uci.edu','CUI',1.00,'us'),
('ucla',NULL,'University of California, Los Angeles','ucla.edu',1,NULL,'universityofcalifornia',NULL,NULL,1,'urn:mace:incommon:ucla.edu','CLU',1.33,'us'),
('ucla-dev',NULL,'University of California, Los Angeles MFA test','ucla.edu',1,NULL,'universityofcalifornia',NULL,NULL,0,'https://shbqa.ais.ucla.edu/idp/shibboleth',NULL,1.00,'us'),
('ucm','UCM','Universidad Complutense de Madrid','ucm.es',0,NULL,'ucm',NULL,NULL,1,'https://www.rediris.es/sir/ucmidp','S9M',1.00,'es'),
('ucmerced',NULL,'University of California, Merced','ucmerced.edu',1,NULL,'universityofcalifornia',NULL,NULL,1,'urn:mace:incommon:ucmerced.edu','UCMER',0.00,'us'),
('uconn',NULL,'University of Connecticut','uconn.edu',1,NULL,'uconn',NULL,NULL,1,'https://shibboleth.uconn.edu/idp/shibboleth','UCW',1.00,'us'),
('ucop',NULL,'University of California, Office of the President','ucop.edu',1,NULL,'universityofcalifornia',NULL,NULL,1,'urn:mace:incommon:ucop.edu',NULL,1.00,'us'),
('ucr',NULL,'University of California, Riverside','ucr.edu',1,NULL,'universityofcalifornia',NULL,NULL,1,'urn:mace:incommon:ucr.edu','CRU',1.00,'us'),
('ucsb',NULL,'University of California, Santa Barbara','ucsb.edu',1,NULL,'universityofcalifornia',NULL,NULL,1,'urn:mace:incommon:ucsb.edu','CUT',1.00,'us'),
('ucsc',NULL,'University of California, Santa Cruz','ucsc.edu',1,NULL,'universityofcalifornia',NULL,NULL,1,'urn:mace:incommon:ucsc.edu','CUZ',1.00,'us'),
('ucsd',NULL,'University of California, San Diego','ucsd.edu',1,NULL,'universityofcalifornia',NULL,NULL,1,'urn:mace:incommon:ucsd.edu','CUS',1.00,'us'),
('ucsf',NULL,'University of California, San Francisco','ucsf.edu',1,NULL,'universityofcalifornia',NULL,NULL,1,'urn:mace:incommon:ucsf.edu','CUN',0.00,'us'),
('udel',NULL,'University of Delaware','udel.edu',1,NULL,'udel',NULL,NULL,1,'https://idp.nss.udel.edu/idp/shibboleth','DLM',1.00,'us'),
('ufl',NULL,'University of Florida','ufl.edu',1,NULL,'flbog','Florida State University System',NULL,1,'https://login.ufl.edu/idp/shibboleth','',5.00,'us'),
('uga',NULL,'University of Georgia','uga.edu',1,NULL,'usg','University System of Georgia',NULL,1,'https://sso.cc.uga.edu/cas/idp','GSL',3.00,'us'),
('uh',NULL,'University of Houston','lib.uh.edu',1,NULL,'uh',NULL,NULL,1,'https://shibboleth.lib.uh.edu/idp/shibboleth','TXH',1.00,'us'),
('uh-new',NULL,'University of Houston','uh.edu',1,NULL,'uh-new',NULL,NULL,0,'https://fedidp.uh.edu/idp/shibboleth',NULL,1.00,'us'),
('uic',NULL,'University of Illinois at Chicago','uic.edu',1,NULL,'uic',NULL,NULL,1,'https://shibboleth.uic.edu/shibboleth','IAX',1.00,'us'),
('illinois','UIUC','University of Illinois at Urbana-Champaign','illinois.edu',1,NULL,'illinois',NULL,NULL,1,'urn:mace:incommon:uiuc.edu','UIU',1.33,'us'),
('uky',NULL,'University of Kentucky','uky.edu',1,NULL,'uky',NULL,NULL,1,'https://ukidp.uky.edu/idp/shibboleth','KUK',1.00,'us'),
('umanitoba',NULL,'University of Manitoba','umanitoba.ca',0,NULL,'umanitoba',NULL,NULL,1,'http://CAF.AD.UMANITOBA.CA/adfs/services/trust','UAT',1.00,'ca'),
('umanitoba-dev',NULL,'University Of Manitoba (Dev)','umanitoba.ca',0,NULL,'umanitoba',NULL,NULL,0,'http://caf-test.adlab.cctest.umanitoba.ca/adfs/services/trust','UAT',1.00,'ca'),
('umaryland',NULL,'University of Maryland, Baltimore','umaryland.edu',1,NULL,'umaryland',NULL,NULL,0,'https://webauth.umaryland.edu/idp/shibboleth',NULL,1.00,'us'),
('umass',NULL,'University of Massachusetts Amherst','umass.edu',1,NULL,'umass',NULL,NULL,1,'https://webauth.umass.edu/idp/shibboleth','AUM',1.00,'us'),
('umd',NULL,'University of Maryland, College Park','umd.edu',1,NULL,'umd',NULL,NULL,1,'urn:mace:incommon:umd.edu','UMC',1.00,'us'),
('umdl-umich',NULL,'University of Michigan Library IT, Digital Library Production Service, Digital Conversion Unit','umdl.umich.edu',1,NULL,'umdl-umich',NULL,NULL,2,NULL,NULL,1.00,'us'),
('unc',NULL,'University of North Carolina at Chapel Hill','unc.edu',1,NULL,'unc',NULL,NULL,1,'urn:mace:incommon:unc.edu','NOC',1.33,'us'),
('unf',NULL,'University of North Florida','unf.edu',1,NULL,'flbog','Florida State University System',NULL,1,'https://shib.unf.edu/idp/shibboleth','',5.00,'us'),
('ung',NULL,'University of North Georgia','ung.edu',1,NULL,'usg','University System of Georgia',NULL,1,'https://sso.ung.edu/simplesaml2','GSL',3.00,'us'),
('unh',NULL,'University of New Hampshire','unh.edu',1,NULL,'unh',NULL,NULL,1,'https://mylogin.unh.edu/secureauth74','NHM',1.00,'us'),
('unimelb',NULL,'University of Melbourne','unimelb.edu.au',0,NULL,'unimelb',NULL,NULL,1,'https://idp.unimelb.edu.au/openathens','UMV',1.00,'au'),
('union',NULL,'Union College','union.edu',1,NULL,'union',NULL,NULL,1,'https://sso.union.edu/idp/shibboleth','ZWU',0.67,'us'),
('universityofcalifornia','UCAL','University of California','universityofcalifornia.edu',1,NULL,'universityofcalifornia',NULL,NULL,2,NULL,NULL,1.00,'us'),
('unl',NULL,'University of Nebraska - Lincoln','unl.edu',1,NULL,'unl',NULL,NULL,1,'https://shib.unl.edu/idp/shibboleth','LDL',1.00,'us'),
('unlv',NULL,'University of Nevada - Las Vegas','unlv.edu',1,NULL,'unlv',NULL,NULL,1,'https://login.unlv.edu/FIM/sps/MyShib/saml20','UNL',1.00,'us'),
('unm',NULL,'University of New Mexico','unm.edu',1,NULL,'unm',NULL,NULL,1,'https://unmpidp.unm.edu/idp/shibboleth','IQU',1.00,'us'),
('unr',NULL,'University of Nevada, Reno','unr.edu',1,NULL,'unr',NULL,NULL,1,'https://idp2.unr.edu/idp/shibboleth','NNY',1.00,'us'),
('unsw',NULL,'UNSW Sydney','unsw.edu.au',0,NULL,'unsw',NULL,NULL,1,'https://aaf.unsw.edu.au/idp/shibboleth','',1.00,'au'),
('unt',NULL,'University of North Texas','unt.edu',1,NULL,'unt',NULL,NULL,1,'https://sso.unt.edu/idp/shibboleth','INT',1.00,'us'),
('uoguelph',NULL,'University of Guelph','uoguelph.ca',0,NULL,'uoguelph',NULL,NULL,1,'https://idp.identity.uoguelph.ca/idp/shibboleth','U3G',1.00,'ca'),
('umich','UOM','University of Michigan','umich.edu',1,NULL,'umich',NULL,NULL,1,'https://shibboleth.umich.edu/idp/shibboleth','EYM',1.33,'us'),
('uoregon',NULL,'University of Oregon','uoregon.edu',1,NULL,'uoregon',NULL,NULL,1,'https://shibboleth.uoregon.edu/idp/shibboleth','ORU',1.00,'us'),
('uottawa',NULL,'University of Ottawa','uottawa.ca',0,NULL,'uottawa',NULL,NULL,1,'http://fca-caf.uottawa.ca/adfs/services/trust','OTZ',1.00,'ca'),
('upenn',NULL,'University of Pennsylvania','upenn.edu',1,NULL,'upenn',NULL,NULL,1,'https://idp.pennkey.upenn.edu/idp/shibboleth','PAU',1.33,'us'),
('uq',NULL,'The University of Queensland','uq.edu.au',0,NULL,'uq',NULL,NULL,1,'https://auth.uq.edu.au/idp/saml2/idp/metadata.php','YQU',1.00,'au'),
('uregina',NULL,'University of Regina','uregina.ca',0,NULL,'uregina',NULL,NULL,1,'https://idp.uregina.ca/idp/shibboleth',NULL,1.00,'us'),
('usask',NULL,'University of Saskatchewan','usask.ca',0,NULL,'usask',NULL,NULL,0,'https://idp.usask.ca/idp/shibboleth',NULL,1.00,'us'),
('usc',NULL,'University of Southern California','usc.edu',1,NULL,'usc',NULL,NULL,1,'urn:mace:incommon:usc.edu','CSL',1.33,'us'),
('usf',NULL,'University of South Florida','usf.edu',1,NULL,'flbog','Florida State University System',NULL,1,'urn:mace:incommon:usf.edu','',5.00,'us'),
('usg',NULL,'University System of Georgia','usg.edu',1,NULL,'usg',NULL,NULL,2,NULL,'GSL',3.00,'us'),
('usu',NULL,'Utah State University','usu.edu',1,NULL,'usu',NULL,NULL,1,'https://shibboleth.usu.edu/idp/shibboleth','UUS',0.67,'us'),
('usupress',NULL,'Utah State University Press','usupress.com',1,NULL,'usupress',NULL,NULL,2,NULL,NULL,1.00,'us'),
('uta',NULL,'University of Texas at Arlington','uta.edu',1,NULL,'utexas','The University of Texas',NULL,1,'https://idp.uta.edu/idp/shibboleth','IXA',3.00,'us'),
('utah',NULL,'University of Utah','utah.edu',1,NULL,'utah',NULL,NULL,1,'urn:mace:incommon:utah.edu','UUM',1.00,'us'),
('utdallas',NULL,'University of Texas at Dallas','utdallas.edu',1,NULL,'utexas','The University of Texas',NULL,1,'https://idp.utdallas.edu/idp/shibboleth','IXA',3.00,'us'),
('utep',NULL,'University of Texas at El Paso','utep.edu',1,NULL,'utexas','The University of Texas',NULL,1,'https://shib2.utep.edu/idp/shibboleth','IXA',3.00,'us'),
('utexas','UTEXAS','University of Texas at Austin','utexas.edu',1,NULL,'utexas','The University of Texas',NULL,1,'https://idp.its.utexas.edu/idp/shibboleth','IXA',3.00,'us'),
('uth',NULL,'University of Texas Health Science Center at Houston','uth.edu',1,NULL,'utexas','The University of Texas',NULL,1,'https://shib-idp2.uth.tmc.edu/idp/shibboleth','IXA',3.00,'us'),
('utk',NULL,'University of Tennessee, Knoxville','utk.edu',1,NULL,'utk',NULL,NULL,1,'https://idp.utk.edu/idp/shibboleth','TKN',1.00,'us'),
('utmb',NULL,'University of Texas Medical Branch At Galveston','utmb.edu',1,NULL,'utexas','The University of Texas',NULL,0,'https://idp.utmb.edu/idp/shibboleth','IXA',3.00,'us'),
('utoronto',NULL,'University of Toronto','utoronto.ca',0,NULL,'utoronto',NULL,NULL,1,'https://idpz.utorauth.utoronto.ca/shibboleth','UTO',1.33,'ca'),
('utrgv',NULL,'University of Texas Rio Grande Valley','utrgv.edu',1,NULL,'utexas','The University of Texas',NULL,1,'https://idp.utrgv.edu/idp/shibboleth','IXA',3.00,'us'),
('utsa',NULL,'University of Texas at San Antonio','utsa.edu',1,NULL,'utexas','The University of Texas',NULL,1,'https://sso.it.utsa.edu/idp/shibboleth','IXA',3.00,'us'),
('uuhhs',NULL,'Unitarian Universalist History and Heritage Society','uuhhs.org',1,NULL,'uuhhs',NULL,NULL,2,NULL,NULL,1.00,'us'),
('virginia','UVA','University of Virginia','virginia.edu',1,NULL,'virginia',NULL,NULL,1,'urn:mace:incommon:virginia.edu','VA@',1.33,'us'),
('uvm',NULL,'University of Vermont','uvm.edu',1,NULL,'uvm',NULL,NULL,1,'https://idp.uvm.edu/idp/shibboleth','VTU',1.00,'us'),
('uwaterloo',NULL,'University of Waterloo','uwaterloo.ca',0,NULL,'uwaterloo',NULL,NULL,1,'https://idp.uwaterloo.ca/idp/shibboleth','UWW',1.00,'ca'),
('uwf',NULL,'University of West Florida','uwf.edu',1,NULL,'flbog','Florida State University System',NULL,1,'https://idp.uwf.edu/idp/shibboleth','',5.00,'us'),
('uwyo',NULL,'University of Wyoming','uwyo.edu',1,NULL,'uwyo',NULL,NULL,1,'https://shibboleth.uwyo.edu/idp/shibboleth','WYU',1.00,'us'),
('vanderbilt',NULL,'Vanderbilt University','vanderbilt.edu',1,NULL,'vanderbilt',NULL,NULL,1,'https://sso-login-uat.vanderbilt.edu','TJC',1.00,'us'),
('vassar',NULL,'Vassar College','vassar.edu',1,NULL,'vassar',NULL,NULL,1,'https://shib01.vassar.edu/idp/shibboleth','VXW',0.67,'us'),
('vcu',NULL,'Virginia Commonwealth University','vcu.edu',1,NULL,'vcu',NULL,NULL,1,'https://shibboleth.vcu.edu/idp/shibboleth','VRC',1.00,'us'),
('vt',NULL,'Virginia Tech','vt.edu',1,NULL,'vt',NULL,NULL,1,'urn:mace:incommon:vt.edu','VPI',1.00,'us'),
('washington',NULL,'University of Washington','washington.edu',1,NULL,'washington',NULL,NULL,1,'urn:mace:incommon:washington.edu','WAU',1.33,'us'),
('wayne',NULL,'Wayne State University','wayne.edu',1,NULL,'wayne',NULL,NULL,1,'https://academica.aws.wayne.edu/saml2/trust','EYW',1.00,'us'),
('wesleyan',NULL,'Wesleyan University','wesleyan.edu',1,NULL,'wesleyan',NULL,NULL,1,'https://shibboleth.wesleyan.edu/idp/shibboleth','WLU',0.67,'us'),
('wfu',NULL,'Wake Forest University','wfu.edu',1,NULL,'wfu',NULL,NULL,1,'https://webauth.wfunet.wfu.edu/saml/saml2/idp/metadata.php','EWF',1.00,'us'),
('whitman',NULL,'Whitman College','whitman.edu',1,NULL,'whitman',NULL,NULL,1,'https://idp.whitman.edu/idp/shibboleth','HTM',0.67,'us'),
('wichita',NULL,'Wichita State University','wichita.edu',1,NULL,'wichita',NULL,NULL,1,'https://shib.wichita.edu/idp/shibboleth','KSW',0.67,'us'),
('williams',NULL,'Williams College','williams.edu',1,NULL,'williams',NULL,NULL,1,'https://idp.williams.edu/idp/shibboleth','WCM',0.67,'us'),
('wisc','Wisc','University of Wisconsin - Madison','wisc.edu',1,NULL,'wisc',NULL,NULL,1,'https://login.wisc.edu/idp/shibboleth','GZM',1.00,'us'),
('wlu-ca',NULL,'Wilfrid Laurier University','wlu.ca',0,NULL,'wlu-ca',NULL,NULL,1,'https://idp.wlu.ca/idp/shibboleth','W2U',0.67,'ca'),
('wm',NULL,'William &amp; Mary','wm.edu',1,NULL,'wm',NULL,NULL,1,'https://idp.wm.edu/idp/shibboleth','VWM',1.00,'us'),
('wpi',NULL,'Worcester Polytechnic Institute','wpi.edu',1,NULL,'wpi',NULL,NULL,0,'https://idp.wpi.edu/idp/shibboleth',NULL,1.00,'us'),
('wsu',NULL,'Washington State University','wsu.edu',1,NULL,'wsu',NULL,NULL,1,'https://shibidp.wsu.edu/idp/shibboleth','ws7',1.00,'us'),
('wustl',NULL,'Washington University in St. Louis','wustl.edu',1,NULL,'wustl',NULL,NULL,1,'https://login.wustl.edu/idp/shibboleth','WTU',1.00,'us'),
('wvu',NULL,'West Virginia University','wvu.edu',1,NULL,'wvu',NULL,NULL,1,'https://idp.wvu.edu/idp/shibboleth','WVU',1.00,'us'),
('xula',NULL,'Xavier University of Louisiana','xula.edu',1,NULL,'xula',NULL,NULL,1,'https://idp.xula.edu/openathens','LNX',0.67,'us'),
('yale',NULL,'Yale University','yale.edu',1,NULL,'yale',NULL,NULL,1,'https://auth.yale.edu/idp/shibboleth','YUS',1.33,'us'),
('yorku',NULL,'York University','yorku.ca',0,NULL,'yorku',NULL,NULL,1,'https://shib.yorku.ca/idp/shibboleth',NULL,1.00,'us');

INSERT INTO `ht_collections` VALUES ('AEU','ualberta','ualberta','ualberta','ualberta'),
('AUBRU','uq','uq','uq','uq'),
('AZTES','asu','asu','asu','asu'),
('CHI','uchicago','uchicago','uchicago','uchicago'),
('COO','cornell','cornell','cornell','cornell'),
('CTU','uconn','uconn','uconn','uconn'),
('DEU','udel','udel','udel','udel'),
('FMU','miami','miami','miami','miami'),
('GEU','emory','emory','emory','emory'),
('GRI','getty','getty','getty','getty'),
('GWLA','technicalreports','umich','technicalreports','umich'),
('HVD','harvard','harvard','harvard','harvard'),
('IAU','uiowa','uiowa','uiowa','uiowa'),
('IBC','bc','bc','bc','bc'),
('IDUKE','duke','duke','duke','duke'),
('ILOC','loc','loc','loc','loc'),
('INCSU','ncsu','ncsu','ncsu','ncsu'),
('INNC','columbia','columbia','columbia','columbia'),
('INND','nd','nd','nd','nd'),
('INRLF','universityofcalifornia','universityofcalifornia','universityofcalifornia','berkeley'),
('INU','iu','iu','iu','iu'),
('IPST','psu','psu','psu','psu'),
('ISRLF','universityofcalifornia','universityofcalifornia','universityofcalifornia','ucla'),
('IUCD','universityofcalifornia','universityofcalifornia','universityofcalifornia','ucdavis'),
('IUCLA','universityofcalifornia','universityofcalifornia','universityofcalifornia','ucla'),
('IUFL','flbog','flbog','flbog','flbog'),
('IUIUC','illinois','illinois','illinois','illinois'),
('IUNC','unc','unc','unc','unc'),
('KEIO','keio','hathitrust','keio','hathitrust'),
('LEBAU','aub','aub','aub','aub'),
('MDBJ','jhu','jhu','jhu','jhu'),
('MDL','mndigital','umn','mndigital','umn'),
('MDU','umd','umd','umd','umd'),
('MIU','umich','umich','umich','umich'),
('MMET','tufts','tufts','tufts','tufts'),
('MOU','missouri','missouri','missouri','missouri'),
('MSU','msu','msu','msu','msu'),
('MU','umass','umass','umass','umass'),
('MWICA','clarkart','umich','clarkart','umich'),
('NBB','brooklynmuseum','umich','brooklynmuseum','umich'),
('NBUU','buffalo','buffalo','buffalo','buffalo'),
('NCWSW','wfu','wfu','wfu','wfu'),
('NJP','princeton','princeton','princeton','princeton'),
('NNC','columbia','columbia','columbia','columbia'),
('NNFR','frick','umich','frick','umich'),
('NRLF','universityofcalifornia','universityofcalifornia','universityofcalifornia','berkeley'),
('NWU','northwestern','northwestern','northwestern','northwestern'),
('NYP','nypl','nypl','nypl','nypl'),
('OKS','okstate','okstate','okstate','okstate'),
('OSU','osu','osu','osu','osu'),
('PHC','haverford','haverford','haverford','haverford'),
('PPT','temple','temple','temple','temple'),
('PST','psu','psu','psu','psu'),
('PU','upenn','upenn','upenn','upenn'),
('PUR','purdue','purdue','purdue','purdue'),
('QMM','mcgill','mcgill','mcgill','mcgill'),
('SCU','sc','sc','sc','sc'),
('SRLF','universityofcalifornia','universityofcalifornia','universityofcalifornia','ucla'),
('TXCM','tamu','tamu','tamu','tamu'),
('TXSMTSU','txstate','txstate','txstate','txstate'),
('TXU','utexas','utexas','utexas','utexas'),
('UCBK','universityofcalifornia','universityofcalifornia','universityofcalifornia','berkeley'),
('UCD','universityofcalifornia','universityofcalifornia','universityofcalifornia','ucdavis'),
('UCI','universityofcalifornia','universityofcalifornia','universityofcalifornia','uci'),
('UCLA','universityofcalifornia','universityofcalifornia','universityofcalifornia','ucla'),
('UCM','ucm','ucm','ucm','ucm'),
('UCMR','universityofcalifornia','universityofcalifornia','universityofcalifornia','ucmerced'),
('UCR','universityofcalifornia','universityofcalifornia','universityofcalifornia','ucr'),
('UCSB','universityofcalifornia','universityofcalifornia','universityofcalifornia','ucsb'),
('UCSC','universityofcalifornia','universityofcalifornia','universityofcalifornia','ucsc'),
('UCSD','universityofcalifornia','universityofcalifornia','universityofcalifornia','ucsd'),
('UCSF','universityofcalifornia','universityofcalifornia','universityofcalifornia','ucsf'),
('UFDC','flbog','flbog','flbog','flbog'),
('UIUC','illinois','illinois','illinois','illinois'),
('UIUCL','illinois','illinois','illinois','illinois'),
('UKLOKU','knowledgeunlatched','hathitrust','knowledgeunlatched','hathitrust'),
('UMBUS','umich','umich','umich','umich'),
('UMDB','umich','umich','umich','umich'),
('UMDCMP','milproj-dc-umich','umich','milproj-dc-umich','umich'),
('UMLAW','umich','umich','umich','umich'),
('UMN','umn','umn','umn','umn'),
('UMPRIVATE','ht_private','umich','ht_private','umich'),
('USU','usupress','usu','usupress','usu'),
('UUHHS','uuhhs','umich','uuhhs','umich'),
('UVA','virginia','virginia','virginia','virginia'),
('VIRCU','vcu','vcu','vcu','vcu'),
('WAU','washington','washington','washington','washington'),
('WU','wisc','wisc','wisc','wisc'),
('YALE','yale','yale','yale','yale');
