name: Manual Image Build

on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag
        required: true

jobs:
  build_manual:
    - uses: hathitrust/github_actions/build@v1
      with:
        dockerfile: Dockerfile.prod
        image: ghcr.io/hathitrust/holdings-client-unstable
        tag: ${{ github.event.inputs.tag }}
        push_latest: false
        registry_token: ${{ github.token }}
