name: Docker Build

on:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up tests
        run: ./bin/setup_test.sh

      - name: Run tests
        run: docker-compose run --rm -e MONGOID_ENV=test dev bin/wait-for mariadb:3306 -- bundle exec rspec
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build image and push to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: 'hathitrust/holdings-client-unstable:${{ github.sha }}, hathitrust/holdings-client-unstable:latest'
          file: Dockerfile


