name: Docker Build

on:
  workflow_run:
    workflows: [ 'Run CI']
    branches: [ 'main' ]
    types: [ completed ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - uses: hathitrust/github_actions/build@v1
        with:
          image: ghcr.io/hathitrust/holdings-client-unstable
          dockerfile: Dockerfile.prod
          tag: ${{ github.sha }}
          push_latest: true
          registry_token: ${{ github.token }}
