name: Run CI

on:
  pull_request:
  push:
    branches:
      - main
      - v1.0.x

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up tests
        run: ./bin/setup/setup_test.sh

      - name: Run standardrb
        run: docker-compose run --rm dev bundle exec standardrb

      - name: Run tests
        run: docker-compose run --rm -e MONGOID_ENV=test dev bin/setup/wait-for mariadb:3306 -- bundle exec rspec
