name: Run CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up tests
        run: ./bin/setup_test.sh

      - name: Run rubocop
        run: docker-compose run --rm dev bundle exec rubocop

      - name: Run tests
        run: docker-compose run --rm -e MONGOID_ENV=test dev bin/wait-for mariadb:3306 -- bundle exec rspec


