name: Docker Tag Latest Release

on:
  release:
    types: [ released ]

jobs:
  tag-release:
    runs-on: ubuntu-latest
    steps:
      - uses: hathitrust/github_actions/tag-release@v1
        with:
          registry_token: ${{ github.token }}
          existing_tag: ghcr.io/hathitrust/holdings:${{ github.sha }}
          image: ghcr.io/hathitrust/holdings
          new_tag: ${{ github.event.release.tag_name }}
