name: Docker Tag Latest Release

on:
  release:
    types: [ released ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Tag latest release in DockerHub
      run: |
        docker pull hathitrust/holdings-client-unstable:${{ github.sha }}
        docker tag hathitrust/holdings-client-unstable:${{ github.sha }} hathitrust/holdings-client:${{ github.event.release.tag_name }}
        docker tag hathitrust/holdings-client-unstable:${{ github.sha }} hathitrust/holdings-client:latest
        docker push hathitrust/holdings-client:${{ github.event.release.tag_name }}
        docker push hathitrust/holdings-client:latest
