name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

      - name: Build images for testing
        run: docker compose build

      - name: Install dependencies
        run: docker compose run --rm test bundle install

      - name: Run standardrb
        run: docker compose run --rm test bundle exec standardrb

      - name: Run tests
        run: docker compose run --rm test

      - name: Report to Coveralls
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.7
