name: Run Tests

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Build images for testing
        run: docker compose build

      - name: Install dependencies
        run: docker compose run --rm test bundle install

      - name: Run standardrb
        run: docker compose run --rm test bundle exec standardrb

      - name: Run tests
        run: docker compose run --rm test

      - name: Report to Coveralls
        uses: coverallsapp/github-action@v2
